server:
  port: 8080
spring:
  application:
    name: Gatway-service
  cloud:
    discovery:
      enabled: true
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081
#          predicates:
#            - Path= /clients/**
#        - id: r2
#          uri: http://localhost:8082
#          predicates:
#            - Path= /produits/**

